### ISSUE TITLE
Speed transaction

### ISSUE THREAD

**Issue by sieutran** [derfabsSL/Splinterbuyer#8]
I get the failed many fail buying because of no longer cards is exist. Here is my error:
Errors: The specified market items are no longer available for purchase.

Exactly, I got 40 failed transactions. I think others bot has quicker than our bot.

**Comment by derfabsSL** [comment]
This is most likely because there are people running bots on their own validator nodes, not much that can be done about it unfortunately as they see transactions before anyone else.
To speed up the bot a bit you can try bidding on a small number of cards only.
Or you can just raise your buying prices a bit so you don't have to compete with these bots.
